### PRUEBAS USER
POST http://localhost:3000/api/users/register HTTP/1.1
Content-Type: application/json
 
{
    "name": "asier",
    "age": 35,
    "email": "asier@gmail.com",
    "password": "prueba1010", 
    "city": "madrid",
    "interests": "trading",  
    "allowOffers": "true"
}
### 
POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "asier@gmail.com",
    "password": "prueba1010" 
}

###
PUT http://localhost:3000/api/users/6473d98b6275b318f8dbd8e8 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDczZDk4YjYyNzViMzE4ZjhkYmQ4ZTgiLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NTMxNDA3MCwiZXhwIjoxNjg1MzIxMjcwfQ.9-l5L5t_TZtEJDL19CQO5P4Pyys9O4GO-QxtNiw5vI0

{
    "name": "Asier",
    "age": "35",
    "email": "asier@gmail.com"
}
### 
GET http://localhost:3000/api/webpages/

### MIRAR LAS WEBPAGES
GET http://localhost:3000/api/webpages/
### 
GET http://localhost:3000/api/webpages/search/barcelona
### 
GET http://localhost:3000/api/webpages/search/barcelona/sort
### 
PATCH http://localhost:3000/api/webpages/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer 
{
  "nonEditable": {
    "scoring": [10],
    "reviews": [
      "Buen comercio, lo recomiendo"
    ]
  }
}
### PARA HACER DELETE
DELETE http://localhost:3000/api/users/ 
Authorization: Bearer 



### PRUEBAS ADMIN 
POST http://localhost:3000/api/users/register HTTP/1.1
Content-Type: application/json

{
    "name": "ADMIN",
    "age": "22",
    "email": "ADMIN@ADMIN.com",
    "password": "adminrules", 
    "city": "madrid", 
    "interests": "cripto", 
    "allowOffers": "false",
}
###
POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "ADMIN@ADMIN.com",
    "password": "adminrules" 
}
###
POST http://localhost:3000/api/commerce/register HTTP/1.1
Content-Type: application/json
Authorization: Bearer 
{
    "name": "Alpha",
    "cif": "59748316",
    "address": "alpha 21",
    "email": "alpha@gmail.com", 
    "password": "alpha",
    "contact": "688145976"
}
###
POST http://localhost:3000/api/commerce/register HTTP/1.1
Content-Type: application/json
Authorization: Bearer 
{
    "name": "Regal",
    "cif": "67913452",
    "address": "regal 13",
    "email": "regal@gmail.com", 
    "password": "regal456",
    "contact": "713846175"
}
### 
GET http://localhost:3000/api/commerce/
Authorization: Bearer 
###
GET http://localhost:3000/api/commerce/
Authorization: Bearer 
###
PUT http://localhost:3000/api/commerce/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer 
{
    "name": "Regal",
    "cif": "33445566",
    "address": "vasili 18",
    "email": "regal@live.regal.com", 
    "password": "queenbishop",
    "contact": "682476534"
}
###
DELETE http://localhost:3000/api/commerce/
Authorization: Bearer 

### PRUEBAS MERCHANT 
POST http://localhost:3000/api/commerce/login HTTP/1.1
Content-Type: application/json

{
    "email": "regal@gmail.com",
    "password": "regal456" 
}
###
POST http://localhost:3000/api/webpages/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer 
{
    "city": "madrid",
    "activity": "cripto",
    "title": "Crear una cripto",
    "resumen": "hacer una memecoin para forrarnos" 
}
###
POST http://localhost:3000/api/webpages/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer 
{
    "city": "barcelona",
    "activity": "trading",
    "title": "Trading XAU",
    "reusmen": "operar oro en Metatrader" 
}
### 
GET http://localhost:3000/api/users/madrid
Authorization: Bearer ###     WEBPAGES SUBIR FOTO / TEXTO
POST http://localhost:3000/api/webpages/"pagina"/photos HTTP/1.1 
Content-Type: multipart/form-data; boundary=Boundry
Authorization: Bearer 
--Boundry
Content-Disposition: form-data; name="image"; filename="dunes.png"
Content-Type: image/png

< ./dunes.png
--Boundry--
### 
POST http://localhost:3000/api/webpages/"pagina_a_modificar"/texts HTTP/1.1 
Content-Type: application/json
Authorization: Bearer 
{
    "texts":["buenas", "noches"]
}


##Usuarios
GET http://localhost:3000/api/users/madrid

###
POST http://localhost:3000/api/users/register HTTP/1.1
Content-Type: application/json

{
    "name": "ADMIN",
    "age": "22",
    "email": "ADMIN@ADMIN.com",
    "password": "root", 
    "city": "madrid", 
    "allowOffers": "false",
    "role": "admin"
}

### 
POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "prueba@gmail.com",
    "password": "prueba2023" 
}

###
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Jorge",
    "age": "17",
    "email": "george@gmail.com",
    "password": "georgimola", 
    "city": "valencia", 
    "allowOffers": "true"
}


### 
PUT http://localhost:3000/api/users/"usuario_a_modificar" HTTP/1.1
Content-Type: application/json

{
    "name": "David",
    "age": "27",
    "email": "david@gmail.com",
    "password": "david2023", 
    "city": "barcelona", 
    "allowOffers": "false"
}

###             PRUEBAS MERCHANTS/COMMERCES 
POST http://localhost:3000/api/commerce HTTP/1.1
Content-Type: application/json

{
    "name": "U-tad",
    "cif": "91210899",
    "address": "Goya 5",
    "email": "u-tad@gmail.com", 
    "contact": "689096087"
}

### 

POST http://localhost:3000/api/commerce HTTP/1.1
Content-Type: application/json

{
    "name": "Rolex",
    "cif": "54365299",
    "address": "Peluco 13",
    "email": "rolex@gmail.com", 
    "contact": "629079153"
}
### 

PUT http://localhost:3000/api/commerce/"comercio_a_modificar" HTTP/1.1
Content-Type: application/json

{
    "name": "Nidoo",
    "cif": "54698741",
    "address": "Glass 7",
    "email": "nidoo@gmail.com", 
    "contact": "670735912"
}

### 
GET http://localhost:3000/api/commerce/

###
GET http://localhost:3000/api/commerce/

### 

DELETE http://localhost:3000/api/commerce/

###      

POST http://localhost:3000/api/webpages/ HTTP/1.1
Content-Type: application/json

{
    "webpageId": "",
    "city": "madrid",
    "activity": "cripto",
    "title": "Crear una cripto",
    "summary": "hacer una memecoin para forrarnos", 
    "texts": ["we", "moon"]
}
###
DELETE http://localhost:3000/api/webpages/
### 

POST http://localhost:3000/api/webpages/ HTTP/1.1
Content-Type: application/json

{
    "webpageId": "",
    "city": "madrid",
    "activity": "gaming",
    "title": "Competicion de Call of Duty",
    "summary": "competicion entre 6 equipos en Ifema", 
    "texts": ["lets", "go"]
}

###
GET http://localhost:3000/api/webpages/ HTTP/1.1

###
GET http://localhost:3000/api/webpages/ HTTP/1.1

###     WEBPAGES SUBIR FOTO / TEXTO

POST http://localhost:3000/api/webpages/"webpage_token"/photos HTTP/1.1 
Content-Type: multipart/form-data; boundary=Boundry

--Boundry
Content-Disposition: form-data; name="image"; filename="dunes.png"
Content-Type: image/png

< ./dunes.png
--Boundry--

### 
POST http://localhost:3000/api/webpages/"webpage_token"/texts HTTP/1.1 
Content-Type: application/json

{
    "texts":["hola", "que tal"]
}